.\" # SPDX-FileCopyrightText: Copyright 2026 Red Hat, Inc.
.\" # SPDX-License-Identifier: LGPL-2.1-or-later
.TH GVDB-DUMP 1 "March 2025" "gvdb" "User Commands"
.SH NAME
gvdb-dump \- dump the contents of a gvdb database
.SH SYNOPSIS
.B gvdb-dump
.RB [ \-h ]
.I FILE
.SH DESCRIPTION
.B gvdb-dump
Dump the contents of a gvdb database
.SH OPTIONS
.TP
.B \-h, \-\-help
Show help options
.TP
.I FILE
The gvdb database file to dump.
